### ISSUE TITLE
Scala runtime error

### ISSUE THREAD

**Issue by nssalian** [ehiggs/spark-terasort#10]
Hi,

```
#!/usr/bin/env bash

spark-submit --queue "priority" --master yarn --deploy-mode client --class com.github.ehiggs.spark.terasort.TeraGen /tmp/spark-terasort/target/spark-terasort-1.1-SNAPSHOT-jar-with-dependencies.jar 1g /teraInput

spark-submit --queue "priority" --master yarn --deploy-mode client --class com.github.ehiggs.spark.terasort.TeraSort /tmp/spark-terasort/target/spark-terasort-1.1-SNAPSHOT-jar-with-dependencies.jar /teraInput /teraSort_out

spark-submit --queue "priority" --master yarn --deploy-mode client --class com.github.ehiggs.spark.terasort.TeraValidate /tmp/spark-terasort/target/spark-terasort-1.1-SNAPSHOT-jar-with-dependencies.jar /teraSort_out /teraSort_valid
```
Running the above succeeded, although it ended with an exception that doesn't seem to have been handled.

```
num records: 10000000
checksum: 4c48c175ea9cd9
Exception in thread "main" java.lang.NoSuchMethodError: scala.runtime.ObjectRef.create(Ljava/lang/Object;)Lscala/runtime/ObjectRef;
	at com.github.ehiggs.spark.terasort.TeraValidate$.validate(TeraValidate.scala:108)
	at com.github.ehiggs.spark.terasort.TeraValidate$.main(TeraValidate.scala:61)
	at com.github.ehiggs.spark.terasort.TeraValidate.main(TeraValidate.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:731)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:181)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:206)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:121)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

Have you seen this?

**Comment by ehiggs** [comment]
Hi,
Thanks for your bug report. I haven't seen this. `NoSuchMethodError` sounds like there is a mismatch between a library and an expected use of the library. Which version of scala are you using? And which jvm?

Thanks again!

**Comment by nssalian** [comment]
Hi @ehiggs , thanks for the prompt response. I added a Scala installation and it went away. I didn't know I had to explicitly have scala on the machine for it. But it fixed. It would be perhaps good to add that into the README as a known prerequisite? Feel free to close this. Thanks for the help.

**Comment by ehiggs** [comment]
Thanks for the update.

Spark depends on Scala (it's implemented in Scala) so I thought it would be pulled in by the dependency on spark. Thanks for letting me know about this omission.

**Comment by dastergon** [comment]
I have installed Scala but the error still shows up. Are there any updates on the issue?

**Comment by ehiggs** [comment]
Hi @dastergon, Because @nssalian said "I added a Scala installation and it went away." I hadn't applied much priority to this.

Could you post your stack trace and the versions of java and scala? Thanks.

**Comment by dastergon** [comment]
Hi @ehiggs,

Java Version | 1.8.0_131
Scala Version | version 2.10.5
OS | Ubuntu 16.04.2 LTS
Spark | 1.6.0

The stack trace of TeraValidate:
```
17/07/25 12:12:52 INFO scheduler.DAGScheduler: Job 1 finished: count at TeraValidate.scala:101, took 32.460982 s
17/07/25 12:12:52 ERROR yarn.ApplicationMaster: User class threw exception: java.lang.NoSuchMethodError: scala.runtime.ObjectRef.create(Ljava/lang/Object;)Lscala/runtime/ObjectRef;
java.lang.NoSuchMethodError: scala.runtime.ObjectRef.create(Ljava/lang/Object;)Lscala/runtime/ObjectRef;
	at com.github.ehiggs.spark.terasort.TeraValidate$.validate(TeraValidate.scala:108)
	at com.github.ehiggs.spark.terasort.TeraValidate$.main(TeraValidate.scala:61)
	at com.github.ehiggs.spark.terasort.TeraValidate.main(TeraValidate.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:552)
17/07/25 12:12:52 INFO yarn.ApplicationMaster: Final app status: FAILED, exitCode: 15, (reason: User class threw exception: java.lang.NoSuchMethodError: scala.runtime.ObjectRef.create(Ljava/lang/Object;)Lscala/runtime/ObjectRef;)
17/07/25 12:12:52 INFO spark.SparkContext: Invoking stop() from shutdown hook
```

**Comment by ehiggs** [comment]
Hi, the pom.xml defines a dependency on Scala 2.11:

```xml
<properties>
  <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  <scala.version>2.11.8</scala.version>
  <scala.binary.version>2.11</scala.binary.version>
  <spark.version>2.1.0</spark.version>
</properties>
```

Can you try to install Scala 2.11 and trying it again?

Thanks

**Comment by dastergon** [comment]
I upgraded to the latest Ubuntu LTS version of Scala 2.11.6 but it continues to fail

**Comment by ehiggs** [comment]
I just tried this with Spark 2.2.0 without Hadoop libraries and I wasn't able to reproduce the problem. I pointed Spark to my Hadoop/Yarn env using `SPARK_DIST_CLASSPATH=$($HADOOP_HOME/bin/hadoop --config "$HADOOP_CONF_DIR" classpath)` in the `spark-env.sh`.

I didn't have to install Scala on the machines. But it's curious that the stack trace is failing on `var lastMax = new Array[Byte](10)`. If this fails, how would `TeraInputFormat.scala:77` have worked? It's `private val buffer: Array[Byte] = new Array[Byte](TeraInputFormat.RECORD_LEN)`. 

Or `TeraGen.scala:78`: `val rowBytes: Array[Byte] = new Array[Byte](TeraInputFormat.RECORD_LEN)`

You were able to run TeraGen and TeraSort using the same setup?

**Comment by dastergon** [comment]
Hi @ehiggs, 

My problem was the fact that I was using Spark 1.6. I  updated the pom properties to match my Spark version and it works fine now.

**Comment by ehiggs** [comment]
@dastergon, thanks for reporting back. I'm sorry I didn't spot that earlier when you had given the version you were using.

**Comment by ehiggs** [comment]
Fixed in #11.

**Comment by vyshaliN** [comment]
I have the spark version as 2.1.0 and scala version as 2.11.8 But still I'm getting the error.Let me know if I'm missing anything

**Comment by ehiggs** [comment]
@vyshaliN, Acknowledged. I'll begin by making a Dockerfile / docker-compose setup.

**Comment by vyshaliN** [comment]
When I submitted the job through spark-submit command,it executed well but
when I setup oozie workflow using shell action I(version 0.2) to execute it
as batch job, I'm getting the error.let me know if I'm missing something
