### ISSUE TITLE
TeraGenerate not output to file

### ISSUE THREAD

**Issue by paul-carron** [ehiggs/spark-terasort#13]
Having looked at TeraGenerate.scala it seems the output is not written to file even though the README example includes an output file parameter. Is this correct?

**Comment by lovengulu** [comment]
The output file**s** are written to the directory specified in the command line parameter

**Comment by ehiggs** [comment]
@paul-carron what did you try, what did you expect, and what happened?

**Comment by ehiggs** [comment]
Several months old and no response.
