### ISSUE TITLE
TeraSort: Getting: Final app status: FAILED, exitCode: 16,

### ISSUE THREAD

**Issue by lovengulu** [ehiggs/spark-terasort#14]
I'm using HDP HDP-2.6.4 (with Spark 2.2.0).
The application runs, produces sorted files (which I verified using teraValidate). 
At the end, annoying status: FAILED error appears. 

I don't recall this behavior with HDP 2.4.3 (Spark 1.6.0). 
 
IMHO, the problem/solution is described here:
https://stackoverflow.com/questions/41468833/why-does-spark-exit-with-exitcode-16/41479296

**Comment by ehiggs** [comment]
The issue was probably introduced with #12. Is there still an underlying issue with completion of jobs? Is there an accepted API call to clean up the job?

**Comment by charles2588** [comment]
@ehiggs i replaced system.exit(0) with sc.stop() and i get final status as SUCCEEDED for Yarn
