### ISSUE TITLE
Oozie workflow executing a jar throws "java.lang.NoSuchMethodError: scala.runtime.ObjectRef.create(Ljava/lang/Object;)Lscala/runtime/ObjectRef" Error

### ISSUE THREAD

**Issue by vyshaliN** [ehiggs/spark-terasort#15]
Hi,

I'm using the version of spark 2.1.0 and scala of 2.11.8 I developed the application and the spark-submit is working fine with the application jar. But when I setup a oozie workflow and trigger the spark-submit using shell action(version 0.2),I'm getting the "java.lang.NoSuchMethodError: scala.runtime.ObjectRef.create(Ljava/lang/Object;)Lscala/runtime/ObjectRef" error. Please let me know on which configurations I should have a check.

**Comment by ehiggs** [comment]
Hi,
What command do you use? And xml? If we can fix this, I think it would be a good idea to put your oozie xml in the readme for instructions.

Regarding the issue, [this documentation](https://community.hortonworks.com/questions/25580/scheduling-a-spark-submit-job-using-oozie.html) suggests that you need to use the `<file>` tag to mark jars that are shipped.

**Comment by vyshaliN** [comment]
Hi,

The mistake was that I didn't included the spark home directory while
invoking the job..It's resolved now.

We can close this issue

Regards,
Vyshali

**Comment by ehiggs** [comment]
Ok, great. Thanks for posting the fix. If people run into the same error message they can search for it and find the fix. :)

**Comment by abhi02051992** [comment]
@vyshaliN could you please tell the step wise solution to solve this issue. The one you mentioned that you have included spark-home directory please.
