### ISSUE TITLE
terasort supports only Hadoop file system. It does not accept Linux in memory file system.

### ISSUE THREAD

**Issue by venkyn2** [ehiggs/spark-terasort#19]
Terasort only accepts hdfs path, it does accept OS path to sort. is that because of newAPIHadoopFile? 

Terasort syntax:
```
./bin/spark-submit --class com.github.ehiggs.spark.terasort.TeraSort
path/to/spark-terasort/target/spark-terasort-1.0-SNAPSHOT-jar-with-dependencies.jar 
file://$HOME/data/terasort_in file://$HOME/data/terasort_out
```

```scala
val dataset = sc.newAPIHadoopFile[Array[Byte], Array[Byte], TeraInputFormat](inputFile)
```

**Comment by ehiggs** [comment]
Hi, a "hadoop file" really means a directory with individual files called "part files". You should be able to use spark terasort on OS paths using file:// as a URL scheme. 

What command are you running and what error do you see?

**Comment by ehiggs** [comment]
Closing as >1month with no response from reporter. 

Please reopen this if it's still an issue.
