### ISSUE TITLE
Add to maven central

### ISSUE THREAD

**Issue by mauriciojost** [ehiggs/spark-terasort#4]
Wouldn't it be awesome if your example could be run in just one line from spark-submit?

**Comment by ehiggs** [comment]
That's a good idea! Thanks!

**Comment by ehiggs** [comment]
I set everything up for adding this to Maven Central under com.github.ehiggs.spark-terasort but when I deploy the project the scaladocs aren't converted to javadoc so the Central Repository won't let me release it.

Some on IRC (#scala on freenode) recommend using sbt but that seems like overkill.

**Comment by mauriciojost** [comment]
No need to keep this open forever, closing it.
