### ISSUE TITLE
Works out of the box but how to extract and interpret the numbers?

### ISSUE THREAD

**Issue by dr-riz** [ehiggs/spark-terasort#5]
Fellow Experts,

Super pleased to get it up and running in no time. But, how do I:
- extract and interpret the numbers? if they are good or bad?
- tell if spark has been properly tuned?

Thanking in advanced.

**Comment by ehiggs** [comment]
Hi @dr-riz, these are fundamental questions that this repo hopes to help answer. But it's only a single datapoint (or a small collection). It can't give you a comprehensive answer to the questions.

If you're unsure about the configuration and performance characteristics, try picking up Brendan Gregg's book ["Systems Performance"](https://www.amazon.co.uk/gp/product/0133390098/ref=as_li_ss_tl?ie=UTF8&camp=1789&creative=390957&creativeASIN=0133390098&linkCode=as2&tag=deirdrestraug-20). And/or check out [his blog](http://www.brendangregg.com/) which has great presentations like [this one](http://www.slideshare.net/brendangregg/acm-applicative-system-methodology-2016).

In any event, Terasort, in my experience, is largely driven by the performance of the shuffle stage. Shuffle is often disk bound if it's spilling to disk. If you manage to get to stop spilling to disk, then it becomes network bound. If you're concerned about read and write speeds, try DFSIO and distcp.
